version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "./.github/actions/setup-python-dependencies"
    commit-message:
      prefix: "deps(github-actions)"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "Europe/London"
    target-branch: "main"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "npm"
    directory: "/dashboard"
    commit-message:
      prefix: "deps(typescript)"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "Europe/London"
    target-branch: "main"
    groups:
      typescript:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "pip"
    directory: "tests"
    commit-message:
      prefix: "deps(python-tests)"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "Europe/London"
    target-branch: "main"
    groups:
      python-tests:
        patterns:
          - "*"
