name: "Setup Python Dependencies"
description: "Installs python dependencies for the project"

runs:
  using: "composite"
  steps:
    - name: Install Python and UV
      uses: astral-sh/setup-uv@v5.3.0
      with:
        pyproject-file: "tests/pyproject.toml"
        enable-cache: true
    - name: Set up Just
      uses: extractions/setup-just@v2
    - name: Install Poetry Dependencies
      shell: bash
      run: just tests::install
