dirs:
  - ./
  - ./docs
excludedFiles:
  - ./CHANGELOG.md
aliveStatusCodes:
  - 200
ignorePatterns:
  - pattern: "^http://localhost:8000/repo-overseer.*$"
  - pattern: "^./src/data/repositories.json.*$"
